#!/usr/bin/env python


import os
import datetime


def current_date():
    return datetime.datetime.now().strftime("%Y-%m-%d")


def check_users():
    current_year = datetime.datetime.now().strftime("%Y")
    current_month = datetime.datetime.now().strftime("%b")
    current_day = datetime.datetime.now().strftime("%d")
    with open('/var/log/lock_users/'+current_date() + '/connected_users_'+current_date()+'.txt', 'r') as file:
        lines = file.readlines()
    lines = [l.strip('\n') for l in lines ]
    users = {}
    locked_users = []
    yes_to_all = False
    user_index = 8
    ip_index = 10
    month_index = 0;
    day_index = 1;
    clock_index = 2;
    for item in lines:
        u = item.split(' ')
	is_connected_today = (u[month_index] == current_month) and (u[day_index] == current_day)
        if (not u[ip_index] in users):
            users[u[ip_index]] = u[user_index] + "," + u[month_index] + "," + u[day_index] + "," + u[clock_index]

        elif not users[u[ip_index]].split(",")[0] == u[user_index] and not u[ip_index][0:2]=='10'\
              and not u[user_index] == 'root' and not users[u[ip_index]] == 'root':
            if is_connected_today and u[month_index] == users[u[ip_index]].split(',')[1] and u[day_index] == users[u[ip_index]].split(',')[2] \
              and u[clock_index].split(":")[0] == users[u[ip_index]].split(",")[3].split(":")[0]:
                time_delta = abs(int(users[u[ip_index]].split(",")[3].split(":")[1]) - int(u[clock_index].split(":")[1]))
                print(u[user_index] + " and " + users[u[ip_index]].split(',')[0] + " is connected by same ip " + u[ip_index] + " in " + str(time_delta) + " minutes")
                if not yes_to_all:
                    #answer = raw_input("Do you want to lock the users? [yes|no] (default is no): ")
                    if True: 
                        with open('/var/log/lock_users/'+current_date()+'/locked_users_'+current_date()+'.txt', 'a+') as file:
                            if not u[user_index] in locked_users:
                                #os.system('usermod -L ' + u[user_index])
                                print('user ' + u[user_index] + ' is locked')
                                file.write(u[user_index] + '\n') 
                                locked_users.append(u[user_index])
                            if not users[u[ip_index]].split(',')[0] in locked_users:
                                #os.system('usermod -L ' + users[u[ip_index]].split(',')[0])
                                print('user ' + users[u[ip_index]].split(',')[0] + ' is locked')
                                file.write(users[u[ip_index]].split(',')[0] + '\n')
                                locked_users.append(users[u[ip_index]].split(',')[0])
    return users



if __name__ == '__main__':
    number_of_lines = 200000
    cmd = "tail -n" + str(number_of_lines) + " /var/log/secure | grep Accepted | awk '{$4=$5=$6=$7=$8=$10=$12=$13=$14=$15=\"\"; print $0}'"
    os.system('mkdir -p /var/log/lock_users/'+current_date())
    os.system("ssh compute-0-1 " + cmd + " 1> " + "/var/log/lock_users/"+current_date() +  "/connected_users_"+current_date()+".txt")
    users = check_users()
    #print(users)
    #get_mac_addresses(users)
    

